# Generated by Django 5.0.1 on 2024-02-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobdescription', models.FileField(upload_to='media/jobdescription')),
                ('skills', models.IntegerField(default=0)),
                ('education', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumes', models.FileField(upload_to='media/resumes')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
