# Generated by Django 5.0.1 on 2024-02-04 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='jobdescription',
            field=models.FileField(upload_to='jobdescription'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resumes',
            field=models.FileField(upload_to='resumes'),
        ),
    ]
