# Generated by Django 5.0.1 on 2024-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_hruser_text_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hruser',
            old_name='text_content',
            new_name='jd_text_content',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_text_content',
            field=models.FileField(blank=True, upload_to='resume_texts'),
        ),
        migrations.AlterField(
            model_name='hrmanagerid',
            name='HR_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
