# Generated by Django 5.0.1 on 2024-02-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_jobdescription_user_remove_resume_user_hr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
    ]
