# Generated by Django 5.0.1 on 2024-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_text_content_hruser_jd_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmanagerid',
            name='HR_id',
            field=models.CharField(max_length=100),
        ),
    ]
