# Generated by Django 5.0.1 on 2024-02-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_hrmanagerid_hr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_text_content',
        ),
    ]
