# Generated by Django 5.0.1 on 2024-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_resume_resume_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_text_content',
            field=models.FileField(blank=True, upload_to='resume_texts'),
        ),
    ]
