# Generated by Django 5.0.1 on 2024-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_resume_resume_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='r_text_content',
            field=models.ManyToManyField(related_name='hr_users_r_text_content', to='base.resume'),
        ),
    ]
