# Generated by Django 5.0.1 on 2024-02-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_hruser_r_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hruser',
            name='r_text_content',
        ),
    ]
