# Generated by Django 5.0.1 on 2024-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_hruser_r_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_text_content',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
